# eegpt_causal.yaml
data:
  shift_dir: ../datasets/downstream/CHB_MIT_Scalp_EEG/processed_data/shifted
  batch: 32
  val_ratio: 0.2
  interpolation_len: 256

model:
  pretrain_ckpt: ../checkpoint/eegpt_mcae_58chs_4s_large4E.ckpt  # 若不需要可删
train:
  epochs: 100
  lr: 3e-5
  gpu: [0]
